#配置端口号
server:
  port: 9090
#配置工程名称
spring:
  application:
    name: user-service-provider
#配置数据库信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmtest?characterEncoding=UTF-8
    username: root
    password: root
#配置实体类的别名
mybatis:
  type-aliases-package: com.itheima.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9092/eureka/
