spring:
  application:
    name: eureka
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9092/eureka/
    fetch-registry: false
    register-with-eureka: false